# Generated by Django 4.1.9 on 2023-06-04 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=100)),
                ('emp_code', models.CharField(default='', max_length=3)),
                ('mobile', models.IntegerField(default='', max_length=15)),
                ('image', models.FileField(blank=True, upload_to='uploaded-images/')),
            ],
        ),
    ]
